"""add tag column

Revision ID: 39528ce93eec
Revises: b4ba4f06ea33
Create Date: 2026-07-16 23:50:42.172925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39528ce93eec'
down_revision: Union[str, Sequence[str], None] = 'b4ba4f06ea33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tag')
    # ### end Alembic commands ###
